import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { Heading, Text, Box,AbsoluteCenter, Container, VStack, SimpleGrid, Center, Button, AspectRatio, Alert, AlertIcon, useToast } from '@chakra-ui/react'
import { getCloudinaryImage, getCloudinaryImageBlur } from '../util/cloudinaryImageRetreival';

import Navbar from '../components/navbar'
import NextLink from 'next/link'

import SideBar from '../components/sidebar.js' 


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Box  height={'100vh'} bg={'yellow.300'}>
      <Head>
        <title>Nekosero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box>
        <SideBar />
      </Box>

      <Box>
        <AbsoluteCenter mt={{base: -10, md: 0, lg: 'auto'}} ml={{base:0, lg: 60}}>
          <NextLink href='/about'>
            <Image
              src={getCloudinaryImage('nekosero1.svg')} 
              alt="Nekosero Brand Logo"
              width={300}
              height= {300}
              priority
              placeholder="blur"
              
              blurDataURL={getCloudinaryImageBlur('nekosero1.svg')}
              />
            </NextLink>
        </AbsoluteCenter>
        
      </Box>

    </Box>
  )
}
